name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Checkout the repo"
        uses: actions/checkout@v4
      - name: "Build the zip file using the build script"
        shell: pwsh
        run: .\scripts\build.ps1
      - name: "Create a release"
        uses: ncipollo/release-action@v1
        with:
          artifacts: "deploy/*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "release"
        


